### ISSUE TITLE
Customize theme

### ISSUE THREAD

**Issue by XavierLeTohic** [sachinraja/trpc-playground#49]
Is there or will be a way to customize the code editor's theme? In the current version I can't see what I'm selecting because the highlight color is the same as the background. I'm on Chrome on Mac.

Let me know if you need help on that I could open a PR

**Comment by MatsDK** [comment]
Thanks for reporting this issue, I found a workaround that makes the highlighted text visible. Adding the following styles to a global CSS file worked for me.
```css
.cm-activeLine {
  background-color: rgba(var(--secondary-color-triplet), .5)  !important;
}
```
